---
name: Test this action

on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check changed files
        id: diff
        run: |
          # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
          FIRST_COMMIT=$( git log --pretty=format:%H main.. | tail -n 1 )
          CURRENT_COMMIT=$( git log --pretty=format:%H main.. | head -n 1 )
          export DIFF=$( git diff --name-only $FIRST_COMMIT $CURRENT_COMMIT )
          echo "$DIFF"
          # Escape newlines (replace \n with %0A)
          echo "::set-output name=diff::$( echo "$DIFF" | sed ':a;N;$!ba;s/\n/%0A/g' )"
