---
name: Test this action

on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing the action
        run: |
          git rev-list HEAD^
